### ISSUE TITLE
Vary point size based on octree level

### ISSUE THREAD

**Issue by darkmirage** [pnext/three-loader#26]
In the original Potree viewer, http://www.potree.org/potree/examples/showcase/chiller.html it seems that points from lower levels of detail are rendered larger than points from higher levels of detail, leading to kind of a Google Maps load effect when zooming in. It doesn't seem like the pnext loader does this?

If it does, how do I configure the point sizes to use at different levels of zoom. If it doesn't how hard would it be to implement this?

**Comment by hccampos** [comment]
@darkmirage This is defined by the `pointSizeType` property of the `PointCloudMaterial`. By default the material is using the adaptize sizing like in Potree.

https://github.com/pnext/three-loader/blob/dfdbba58ebf60e6e7bc83ee0ed9ae4b241ffedae/src/materials/point-cloud-material.ts#L214
https://github.com/pnext/three-loader/blob/dfdbba58ebf60e6e7bc83ee0ed9ae4b241ffedae/src/materials/enums.ts#L1
