### ISSUE TITLE
Use Potree in Angular

### ISSUE THREAD

**Issue by sebdurrbach** [pnext/three-loader#56]
I have to integrate Potree in an Angular project but I'm running into various problems, partly due to how it's been designed, and on another hand to my lack of experience in development. So I've read the issue on the Potree Github page about the seperation of the UI and engine, and sadly it's gone nowhere since early 2018.

But i've seen what you've done here and it looks like a very good start in this way, though I'd need to implement most of the different controls available in the main Potree project and I don't really know where to start...  

Could you tell me in broad lines what would it takes to use what you've done in an Angular project and to add more functionalities to it ? Thanks.

**Comment by geoff-harper** [comment]
`Viewer.ts` in the examples dir is a good place to start. Anything you want to add can be done directly with the three.js lib
