### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by pjurczynski** [pnext/three-loader#62]
Hello dear developers,
I hope you find this project useful as I do. I'm more than happy to see the interest in not only using it but also participating in the evolution. I saw quite a bunch of interesting PRs and helpful dependency updates. Good job community!

That being said... You can do even more! You, who can make decisions with community needs in mind. You, who is determined to take this project to the next level. We want you to join the maintainers' force! Post to this thread if you feel you can help! (or come to gitter chat https://gitter.im/pnext/org)

Thank you for your attention, and happy Point Cloud Loading!

**Comment by fahadm** [comment]
Hi! I would be up for helping and maintaining.

**Comment by pjurczynski** [comment]
Thanks for your interest. We'll contact you soon.

**Comment by pjurczynski** [comment]
I'm happy to announce that @fahadm will help us maintain the lib! Thanks a lot and welcome aboard!
