### ISSUE TITLE
EDL Support

### ISSUE THREAD

**Issue by alec-g** [pnext/three-loader#66]
Hey, just wondering if this port currently supports EDL (eye-dome lighting) I have seen that the point-cloud-material has a useEDL paramater but this does not seem to do anything?

**Comment by alec-g** [comment]
Figured out the EDL implementation should be in the viewer itself as it is a post processing shader, was able to setup a screen pass to accomplish these.

**Comment by seonglae** [comment]
Do you have any Implementation EDL with three-loader?

**Comment by iconnary** [comment]
Bump - can anyone point to a sample EDL implementation?

**Comment by nightvisi0n** [comment]
Hi @alec-g, would be really great if you could give as a hint how you implemented the screen pass. Thanks a lot!
