### ISSUE TITLE
Add support for Potree 2.0 format

### ISSUE THREAD

**Issue by fahadm** [pnext/three-loader#79]
As Potree 2.0 has been announced,it came with a new format, as of right now three-loader doesn't support this format.
##TODO List
- [ ] Add support for Octree 1_8 loader
- [ ] Add an example with the new format

**Comment by midnight-dev** [comment]
Just a heads up... The loader name might change in the near future to be less confusing with respect to versioning. That is, it may be dropping the 1_8 moniker. If you can't find it, look for `OctreeLoader.js` instead.

**Comment by potree** [comment]
Already happened in the "compression" branch, where the loader for the 2.0 format, compressed and uncompressed, can be found here: https://github.com/potree/potree/tree/compression/src/modules/loader/2.0

**Comment by fahadm** [comment]
Hey @potree Do you guys have a spec with all possible fields in the json attributes? (adding types explicitly every time the compiler complaints is turning out to be quite annoying).

**Comment by m-schuetz** [comment]
No spec, the createMetadata function might help, though: https://github.com/potree/PotreeConverter/blob/da93ec26411b82ffbf799daf5ac56608ef988bf8/Converter/src/indexer.cpp#L245

The "encoding" attribute can be "BROTLI" for brotli compressed data, or anything else for default uncompressed data. 

If brotli compression is enabled, this function will encode the attribute data for each node accordingly: https://github.com/potree/PotreeConverter/blob/da93ec26411b82ffbf799daf5ac56608ef988bf8/Converter/src/indexer.cpp#L1153

What happens is that attributes will be realigned into a structure of arrays format, see [toStructOfArray](https://github.com/potree/PotreeConverter/blob/da93ec26411b82ffbf799daf5ac56608ef988bf8/Converter/src/indexer.cpp#L969) and position and rgb colors will be encoded in morton code. Position will be 16 byte morton code, rgb 8 byte morton code. The extra bytes don't really matter because compression efficiently gets rid of zero bytes.
https://github.com/potree/potree/blob/compression/src/modules/loader/2.0/DecoderWorker_brotli.js then shows you how brotli compressed data can be decompressed.

**Comment by dddpt** [comment]
Looking forward to Potree 2.0 format support, will probably switch to `three-loader` for our react app once this is up :+1:

**Comment by Higuy8000** [comment]
Also looking forward to 2.0 support!

**Comment by fahadm** [comment]
For anyone wondering, I haven't given up on this (although I got busy with other stuff this year but do have a partly working branch), expect something in the coming weeks.

**Comment by arjan-kuiper** [comment]
@fahadm is support for 2.0 expected to be available anytime soon?

**Comment by fahadm** [comment]
Yes, unfortunately, I got very busy right after that message and wasn't able to get anything done, but now I plan on spending a significant amount of time working on it for the next few days to get this across the finish line :).

**Comment by Frander** [comment]
Hello, any notice about this?

**Comment by shiukaheng** [comment]
Created a [fork](https://www.npmjs.com/package/potree-loader) to use for the time being, not creating a pull request yet since I've also introduced some other changes that might cause compatibility issues.

**Comment by fahadm** [comment]
Nice Work! 

I would love to see a PR (when ever it is done, I was never able to finish this as I always had other more high priority work to do),
 and maybe you can also become a co-contributor for this project.

**Comment by shiukaheng** [comment]
@fahadm Thanks! Sure, but to be honest the library is quite complex and it took me more than a week to only partially understand the code and get it working. The original Potree code was even harder to read. Would be great if we could talk about how its structured / each part interacts with each other, and perhaps as one of the future contributions add proper TSDocs for the library!

**Comment by fahadm** [comment]
@shiukaheng Sure, we can talk sometime (not exactly sure how I can contact you though), I think in general I have a pretty good idea of how everything interacts with one another. And yes I also think tsdocs are important :sweat_smile:

**Comment by shiukaheng** [comment]
Dm'ed on twitter

**Comment by geoff-harper** [comment]
Tangentially related, I see that @shiukaheng's fork has three updated to 0.138.x, any word on doing the same in this version? I have several other three libs that have kept the three version current so I've had to keep those locked into old versions as well. Bringing three up to current here would be huge for me personally

**Comment by tbyholm** [comment]
> @fahadm Thanks! Sure, but to be honest the library is quite complex and it took me more than a week to only partially understand the code and get it working. The original Potree code was even harder to read. Would be great if we could talk about how its structured / each part interacts with each other, and perhaps as one of the future contributions add proper TSDocs for the library!

Hello,

I've been trying this quite a lot and it seems to work well, but for some reason I get no output on chrome/android. I noticed you have changed the shaders a little bit, maybe it has something to do with this?

-Thomas

**Comment by arjan-kuiper** [comment]
@tbyholm You should use [this fork](https://github.com/shiukaheng/potree-loader). It has support for Potree 2.0 and also has fixed shaders to work on Android and various other browsers.

**Comment by tbyholm** [comment]
> @tbyholm You should use [this fork](https://github.com/shiukaheng/potree-loader). It has support for Potree 2.0 and also has fixed shaders to work on Android and various other browsers. The fork is based on this repo.

That's the one I used and modified a little but maybe there has been fixes in the last three weeks ?

**Comment by shiukaheng** [comment]
I tested it on android and it worked alright. The shaders should be functionally the same, but I updated to WebGL2 so I modified the shaders to use GLSL 300 es, which just has a slightly different syntax. Can you attach some logs to see what errors you are getting?

**Comment by tbyholm** [comment]
> I think I tested it on android some time ago and it worked alright, not entirely sure about that though. The shaders should be functionally the same, but I updated to WebGL2 so I modified the shaders to use GLSL 300 es, which just has a slightly different syntax. Can you attach some logs to see what errors you are getting?

I will need to set up some debugging for the phone, with the normal version of three-loader there has never been any problem with Chrome on Android, so I haven't even had to setup any debugging env. and our main usage is not on phones. It seems like the cloud is loading and trying to display something but nothing is output on the screen.

Br,
Thomas

**Comment by tbyholm** [comment]
> I think I tested it on android some time ago and it worked alright, not entirely sure about that though. The shaders should be functionally the same, but I updated to WebGL2 so I modified the shaders to use GLSL 300 es, which just has a slightly different syntax. Can you attach some logs to see what errors you are getting?

THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: invalid shaders

VERTEX

ERROR: 0:130: 'round' : Name of a built-in function cannot be redeclared as function
