### ISSUE TITLE
Output directory not built when pulling in from npm

### ISSUE THREAD

**Issue by geoff-harper** [pnext/three-loader#97]
Hopefully just a quick clarification. I'm currently running v0.2.3 as I'm locked to three r124.

![Screenshot 2021-06-16 145207](https://user-images.githubusercontent.com/7593910/122276104-72c5d380-ceb2-11eb-83dd-27be4c2ff308.png)

This is the directory after a fresh install. The typings value is pointed at `build/declarations/index.d.ts` in package.json which doesn't exist in my instance. I was wondering why it doesn't come built from npm? Trying to build manually errors out pretty substantially.

Edit: rolled back to 0.2.2 and the declarations dir is back

**Comment by fahadm** [comment]
Ah, good eye, it seems that whenever I publish via yarn, it omits the directory, if you really need the declarations directory, I can include it in the future.

In the mean time, maybe use 0.2.3-beta.2 which includes the directory and is on r124 ( there is no difference between 0.2.3 and the beta package)

**Comment by geoff-harper** [comment]
Thanks for the info and quick turn around. I'll give that a go for now and hopefully get up to r128 soon

**Comment by Higuy8000** [comment]
@fahadm It seems this is still an issue. I just installed the latest version off of npm, and the build directory is missing the `declerations/index.d.ts` file, resulting in a `Could not find a declaration file for module '@pnext/three-loader'.` error when trying to import any classes from the module... unless I'm missing something?
